platform :ios, '9.3'
use_frameworks!

target 'SwiftyKlotski_Example' do
  pod 'SwiftyKlotski', :path => '../'

  target 'SwiftyKlotski_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.4'
    pod 'Nimble', '~> 7.3.4'
  end
end
