use_frameworks!

target 'SwiftyKlotski_Example' do
  pod 'SwiftyKlotski', :path => '../'

  target 'SwiftyKlotski_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
