# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: objective-c
# xcode_sdk: iphonesimulator9.3
# cache: cocoapods
podfile: Example/Podfile
before_install:
  - pod repo update
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SwiftyKlotski.xcworkspace -scheme SwiftyKlotski-Example -sdk iphonesimulator12.0 -destination 'platform=iOS Simulator,name=iPhone X,OS=12.0' ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
